namespace Sarcophagus
{
	delegate void PageChangedDelegate(PageId pageId);

	// 
	// View-Models
	// 

	enum PageId
	{
		Main,
		EditCredential
	};

	[default_interface]
	runtimeclass EditCredentialCommand : Microsoft.UI.Xaml.Input.ICommand
	{
		EditCredentialCommand();
	}
	
	[default_interface]
	runtimeclass CopyCredentialCommand : Microsoft.UI.Xaml.Input.ICommand
	{
		CopyCredentialCommand();
	}
	
	runtimeclass Credential : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
	{
		Credential();
		Credential(String name, String password);

		MainVM MainVM{ get; };

		String Name;
		String Password;
	}

	runtimeclass MainVM
	{
		MainVM();
		static MainVM GetInstance();

		PageId PageId{ get; set; };
		Credential CredentialTemplate{ get; set; };
		Windows.Foundation.Collections.IObservableVector<Credential> Credentials{ get; };

		EditCredentialCommand EditCredentialCommand{ get; };
		CopyCredentialCommand CopyCredentialCommand{ get; };

		event PageChangedDelegate PageChanged;
	}

	// 
	// Views
	// 

	[default_interface]
	runtimeclass MainWindow : Microsoft.UI.Xaml.Window
	{
		MainWindow();
		MainVM MainVM{ get; };
	}

	[default_interface]
	runtimeclass MainPage : Microsoft.UI.Xaml.Controls.Page
	{
		MainPage();
		MainVM MainVM{ get; };
	}

	runtimeclass CredEditor : Microsoft.UI.Xaml.Controls.Page
	{
		CredEditor();
		MainVM MainVM{ get; };
	}
}
